name: CI Pipeline

on:
  push:
    branches: [main, assignment-1]
  pull_request:
    branches: [main, assignment-1]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  unit-tests:
    name: Unit Tests with AWS
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      PORT: 8080
      LOG_LEVEL: debug
      FRAGMENTS_DB_TYPE: aws
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SESSION_TOKEN: test
      AWS_S3_BUCKET_NAME: fragments
      AWS_S3_ENDPOINT_URL: http://localhost:4566
      AWS_DYNAMODB_ENDPOINT_URL: http://localhost:8000
      AWS_DYNAMODB_TABLE_NAME: fragments
      HTPASSWD_FILE: tests/.htpasswd

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start LocalStack (S3)
        run: docker run -d -p 4566:4566 --name localstack localstack/localstack

      - name: Start DynamoDB Local
        run: docker run -d -p 8000:8000 --name dynamodb amazon/dynamodb-local

      - name: Wait for LocalStack
        run: |
          echo "Waiting for LocalStack to be ready..."
          until curl -s http://localhost:4566/_localstack/health | grep '"s3": "running"'; do
            echo "Still waiting..."
            sleep 3
          done

      - name: Setup AWS S3 + DynamoDB
        run: ./scripts/local-aws-setup.sh

      - name: Run Unit Tests
        run: env $(grep -v '^#' env.jest | xargs) npm run test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      PORT: 8080
      LOG_LEVEL: debug
      FRAGMENTS_DB_TYPE: aws
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SESSION_TOKEN: test
      AWS_S3_BUCKET_NAME: fragments
      AWS_S3_ENDPOINT_URL: http://localhost:4566
      AWS_DYNAMODB_ENDPOINT_URL: http://localhost:8000
      AWS_DYNAMODB_TABLE_NAME: fragments
      HTPASSWD_FILE: tests/.htpasswd

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start LocalStack (S3)
        run: docker run -d -p 4566:4566 --name localstack localstack/localstack

      - name: Start DynamoDB Local
        run: docker run -d -p 8000:8000 --name dynamodb amazon/dynamodb-local

      - name: Wait for LocalStack
        run: |
          echo "Waiting for LocalStack to be ready..."
          until curl -s http://localhost:4566/_localstack/health | grep '"s3": "running"'; do
            echo "Still waiting..."
            sleep 3
          done

      - name: Setup AWS S3 + DynamoDB
        run: ./scripts/local-aws-setup.sh

      - name: Run Integration Tests
        run: npm run test:integration

  docker-hub:
    name: Build and Push to Docker Hub
    needs: [lint, dockerfile-lint, unit-tests, integration-tests]
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.ref_name == 'assignment-1'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        env:
          DOCKERHUB_REPO: rahkhadi/fragments
          SHA_TAG: sha-${{ github.sha }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.SHA_TAG }}
            ${{ env.DOCKERHUB_REPO }}:${{ github.ref_name }}
            ${{ env.DOCKERHUB_REPO }}:latest
